version: '3'
services:
  pybossa:
    # ubuntu:14.04 installs postgres 9.4 client
    build:
      context: ./docker
      dockerfile: ./pybossa/Dockerfile
      # haven't yet succeeded in getting this source path to work from here
      args:
        - SOURCE_PATH=${SOURCE_PATH:-master}
    depends_on:
      - db
    ports:
      - "3002:80"

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=pybossa
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=pybossa
